name: octron
channels:
  - nvidia/label/cuda-12.6.0
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - pip
  - "cudatoolkit=12.6.0; (sys_platform=='win32' or sys_platform=='linux')"
  - pip:
      - --index-url https://download.pytorch.org/whl/cu126
      - .