name: octron
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - pip
  - cuda=12.6.0  # [win32 or linux]
  - pip:
      - --index-url https://download.pytorch.org/whl/cu126
      - .